services:
  - type: web
    name: sepsis-api
    runtime: docker
    repo: https://github.com/MayurBhama/sepsis_project.git
    plan: free
    region: oregon
    rootDir: .
    dockerCommand: ""   # Use CMD from Dockerfile
    healthCheckPath: /health
    envVars:
      - key: PYTHON_VERSION
        value: 3.10